# tmiDB Production Services
services:
  # --- Core Application Services (from a single image) ---
  tmidb-core:
    image: poi0322/tmidb-core:0.1
    build:
      context: ./tmidb-core
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8020:8020"
    environment:
      - TMIDB_INIT_MODE=setup
      # - TMIDB_INIT_MODE=migrate
      # - TMIDB_INIT_MODE=run
      - TMIDB_INIT_USER=admin
      - TMIDB_INIT_PASSWORD=lighten_0208
      - TMIDB_INIT_ADMIN_TOKEN=XzF9NQhH51NCx-zkg3wJE8KRAK4EBRc8GSn5uxEfQ5VkZeepMs1-Tyx1pnS9vra1TTMM-hCZJM9bfhkDeJ35qw==
    volumes:
      - ./docker-run/tmidb-core/db_data:/var/lib/postgresql/data
      - ./docker-run/tmidb-core/nats_data:/data
      - ./docker-run/tmidb-core/weed_data:/data

  # --- Extension Applications ---

  tmidb-mqtt:
    image: poi0322/tmidb-mqtt:0.1
    build:
      context: ./tmidb-mqtt
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "8083:8083"
    volumes:
      - ./docker-run/tmidb-mqtt/emqx_data:/opt/emqx/data
      - ./docker-run/tmidb-mqtt/emqx_log:/opt/emqx/log
    depends_on:
      - tmidb-core

  tmidb-realtime:
    image: poi0322/tmidb-realtime:0.1
    build:
      context: ./tmidb-realtime
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"
    volumes:
      - ./docker-run/tmidb-realtime/realtime_data:/data
    depends_on:
      - tmidb-core

volumes:
  db_data:
